In [16]:
import numpy as np
#data sets abc and xyz are our inputs - imagine 2 spreadsheet columns of data
a,b,c = 1,2,3
x,y,z = 3,4,5
Inputs = A = np.array([[a,b,c],[x,y,z]])
print Inputs
print np.shape(Inputs)

[[1 2 3]
 [3 4 5]]
(2L, 3L)


In [17]:
#next to the data columns in our spreadsheet we have 
operation1 = np.array([6,7,8])
operation2 = np.array([1.1,2.2,3.3])
Operations = np.array([operation1,operation2])
print Operations
print np.shape(Operations)

[[ 6.   7.   8. ]
 [ 1.1  2.2  3.3]]
(2L, 3L)


In [18]:
#testing the compatibility - performing operations on our inputs
np.dot(Operations,Inputs)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)